### ISSUE TITLE
Leak when establishing connection

### ISSUE THREAD

**Issue by nbigaouette** [inejge/ldap3#47] opened 2020-05-20 20:53 UTC
I'm using this crate in a project that should be 100% up (a Windows service).

Connections are established periodically to perform some actions.

The way the project is architectured, a new (sync) connection is established every time an ldap operation is required, something like the following:
```rust
let ldap_conn = self.bind(self.connect()?, parameters)?;
ldap_conn.search(
        &query,
        ldap3::Scope::SubTree,
        &filter,
        attributes,
    )?;
```

Then `ldap_conn` is going out of scope (and should thus be dropped).

Using macOS's _Instruments_ and `cargo-instruments`I ran a memory leak (with `cargo instruments --limit 60000 --template Leaks --open`).

I've placed generation markers at the period of ldap connections creation and isolated the following backtrace:

```
   0 libsystem_pthread.dylib _pthread_create
   1 project std::sys::unix::thread::Thread::new::h592cab8fcd31da40 /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/sys/unix/thread.rs:68
   2 project std::thread::Builder::spawn_unchecked::h134d2da1c8074b18 /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/thread/mod.rs:492
   3 project std::thread::Builder::spawn::h48a9f7495ba6efa0 /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/thread/mod.rs:386
   4 project tokio_reactor::background::Background::new::haf2838ed3d299015 /Users/nbigaouette/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.12/src/background.rs:75
   5 project tokio_reactor::Reactor::background::had1d3836f2167508 /Users/nbigaouette/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.12/src/lib.rs:364
   6 project tokio::runtime::threadpool::Runtime::reactor::hda8d03c31b7688f0 /Users/nbigaouette/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/mod.rs:177
   7 project tokio_core::reactor::Core::remote::h9f1aae8ac9d65989 /Users/nbigaouette/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:186
   8 project tokio_core::reactor::Core::handle::h615c39a2723d4480 /Users/nbigaouette/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:167
   9 project ldap3::conn::LdapConn::with_settings::h7f914ba203306389 /Users/nbigaouette/.cargo/registry/src/github.com-1ecc6299db9ec823/ldap3-0.6.1/src/conn.rs:210
  10 project project::LdapClient::connect::hd7f7be3a60f42fbd /Users/nbigaouette/project/src/main.rs:163
  11 project _$LT$project..LdapClient$u20$as$u20$project..LdapAccess$GT$::execute::h7196beeb29a23d8d /Users/nbigaouette/project/src/main.rs:96
  18 project std::sys_common::backtrace::__rust_begin_short_backtrace::h0bc3e9aae8c075fa /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/sys_common/backtrace.rs:129
  19 project std::thread::Builder::spawn_unchecked::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h844632ca31721a5d /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/thread/mod.rs:475
  20 project _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h46dde68d861876bc /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panic.rs:318
  21 project std::panicking::try::do_call::hfcc6c29e84830a4d /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panicking.rs:305
  22 project __rust_maybe_catch_panic /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libpanic_unwind/lib.rs:86
  23 project std::panicking::try::h016f17f065cf77aa /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panicking.rs:281
  24 project std::panic::catch_unwind::hc7943b0fdacd3bc1 /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panic.rs:394
  25 project std::thread::Builder::spawn_unchecked::_$u7b$$u7b$closure$u7d$$u7d$::h5291ad7674923a6d /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/thread/mod.rs:474
  26 project core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::hc532a0fb892ac35e /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/ops/function.rs:232
  27 project _$LT$alloc..boxed..Box$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h606f2dced48ff3c4 /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
  28 project _$LT$alloc..boxed..Box$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h0ece8cce658c93ae /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
  29 project std::sys_common::thread::start_thread::h30bbd9f3fb79e88c /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/sys_common/thread.rs:13
  30 project std::sys::unix::thread::Thread::new::thread_start::h7199626a1bd56873 /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/sys/unix/thread.rs:80
  31 libsystem_pthread.dylib _pthread_start
  32 libsystem_pthread.dylib thread_start
```
(Note that I have redacted some lines).

Using macOS's _Activity Monitor_ I can see the file descriptiors number increase with each connection.

I'm not sure where to dig further. Is there something I am not doing properly when establishing my connections? Should I `disconnect()` something? Should tokio be shutdown manually?

Some version information:
* `ldap3`: 0.6.1
* `tokio-core` 0.1.17
* `tokio` 0.1.22

I haven't tried 0.7.0-alpha.7 yet as the API is not compatible.

**Comment by nbigaouette** [comment] 2020-05-20 21:54
I was able to isolate the problem and reproduce it in a simple crate that performs the connections in a loop.

See https://github.com/nbigaouette/ldap3-issue47

Here's a screenshot of _Instruments_ showing the leak of the example crate:

![screenshot](https://user-images.githubusercontent.com/112988/82501236-ec7a6a80-9ac2-11ea-8e1f-1108c5d1d603.png)

**Comment by inejge** [comment] 2020-05-21 06:34
This is a known problem with the later `tokio` 0.1, see #38. You can try the workaround mentioned there (pinning `tokio` to 0.1.11), or, if you're feeling adventurous, use the latest alpha of `ldap3`, which will soon be published as 0.7.

**Comment by inejge** [comment] 2020-05-21 08:25
I tried the following on Linux and couldn't reproduce the leak:

```rust
use std::error::Error;
use std::fs::File;
use std::io::Read;
use std::thread;
use std::time::Duration;

use ldap3::{LdapConn, LdapConnSettings};

fn main() -> Result<(), Box<dyn Error>> {
    let mut ccnt = 0;
    loop {
        let mut self_stat = File::open("/proc/self/stat")?;
        let mut buf = String::new();
        self_stat.read_to_string(&mut buf)?;
        let mut buf_iter = buf.split(" ");
        let vsize = buf_iter.nth(22).unwrap_or("").parse::<u64>()? / 1024;
        let rss = buf_iter.next().unwrap_or("").parse::<u64>()? * 4;
        drop(self_stat);
        ccnt += 1;
        println!("conn: {}, vsize: {}, rss: {}", ccnt, vsize, rss);
        let mut ldap = LdapConn::with_settings(
            LdapConnSettings::new().set_no_tls_verify(true),
            "ldaps://localhost:2636",
        )?;
        ldap.simple_bind("", "")?;
        ldap.unbind()?;
        thread::sleep(Duration::from_millis(100));
    }
}
```

After a hundred connections or so, VSIZE and RSS stabilize and stay unchanged up to 1000, I didn't let it go further. I use `unbind()` to close the connection, but the program behaved the same with `drop(ldap)`.

**Comment by nbigaouette** [comment] 2020-05-21 14:46
Thanks!

I can confirm that the code you posted will show an increase of `vsize` of ~2000 every step when using 0.6.1 but is stable using 0.7.0-alpha7.

I'm running the same code under Instruments to see if I can detect the smaller leak. I'll report to tokio.

**Comment by nbigaouette** [comment] 2020-05-21 16:40
It seems to be happening only on macOS, running under Linux (Docker) seems fine (as reported above).

I've updated the example repo with `tokio-report` branch: https://github.com/nbigaouette/ldap3-issue47/tree/tokio-report

I've opened an issue with tokio: https://github.com/tokio-rs/tokio/issues/2554

**Comment by nbigaouette** [comment] 2020-05-21 18:17
It was reported in https://github.com/tokio-rs/tokio/issues/2554 that:

> The documentation on [`ldap3::LdapConnAsync`](https://docs.rs/ldap3/0.7.0-alpha.7/ldap3/struct.LdapConnAsync.html) says "Dropping the last handle will automatically close the connection.", but that doesn't appear to happen here, then.
> 
> I'm guessing that is the issue.

In the [repo's `tokio-report` branch](https://github.com/nbigaouette/ldap3-issue47/tree/tokio-report) I've expanded the async connection to be as explicit as possible but there is something fishy going on there; If I await the future [returned by the ](https://github.com/nbigaouette/ldap3-issue47/blob/b5736dc/src/main.rs#L25) I get a deadlock...

Could it be that ldap3 is not properly closing the connection?

**Comment by inejge** [comment] 2020-05-21 22:41
Right, there _is_ a bug which wouldn't let the the `select!` loop of the connection terminate after dropping the last handle. Try the `select-exit` branch which contains the fix for loop termination. (I have some doubts about this actually helping in your case, but let's see if it does.)

Doing `await` on the connection task's `JoinHandle` before dropping `ldap` is not expected to work (you'd hang indefinitely since no events would re-poll the tasks futures, except maybe closing the socket.)

Doing `await` _after_ dropping `ldap` should have worked, yes. That's fixed in the `select-exit` branch.

**Comment by nbigaouette** [comment] 2020-05-22 00:53
Thanks for looking into this!

I tried the `select-exit` branch (in the following branch: https://github.com/nbigaouette/ldap3-issue47/tree/tokio-report-select-exit)

The connection can now be awaited after the ldap object being dropped.

Unfortunately there is still a leak somewhere. Running ee1d40d685136a0d03642c042c6b5a8b under Instruments gives me an increase of XXX MB over 2 minutes run.

When inspecting a single 0.1 second period, Instruments tells me there was a 1.52 KB growth (see screenshot in repo's README in `tokio-report-select-exit` branch).

Also, I deployed a version of our project using a pinned version of tokio. When performing 1 ldap search query per second I get the following metrics:
<img width="794" alt="Screen Shot 2020-05-21 at 8 50 09 PM" src="https://user-images.githubusercontent.com/112988/82619753-ce853680-9ba4-11ea-89ad-e25baaf9a8af.png">
<img width="785" alt="Screen Shot 2020-05-21 at 8 50 18 PM" src="https://user-images.githubusercontent.com/112988/82619759-d1802700-9ba4-11ea-971d-c168440f8e7a.png">
So 20 MB increase in RSS and 22 MB increase in VMS overs ~3 hours, which is consistent with a ~1.5 KB leak per request.

**Comment by inejge** [comment] 2020-05-22 07:22
Okay, this seems to confirm my suspicion that the bug in the connection lifecycle did not affect your issue.

I suppose this is all on macOS with a `ldaps://` connection? Try the following:

- macOS, `ldap://` connection
- macOS, `ldap3` with `default-features = false`, `ldap://` connection (this doesn't include TLS support at all)
- Windows, `ldaps://` connection
- Windows, `ldap://` connection
- Windows, `ldap3` with `default-features = false`, `ldap://` connection

I ran your test on Linux under `valgrind` with and without TLS, and it detected no leaks. I don't have direct experience with Windows memory leak debugging, but I've heard good things about [Dr. Memory](http://drmemory.org/).

**Comment by nbigaouette** [comment] 2020-05-22 16:54
I was able to reproduce using an openldap running inside docker. That should help my testing.

Here's a `docker-compose.yml` file that I use:

```yaml
version: "3.8"

services:
  ldap:
    image: osixia/openldap:1.3.0
    container_name: openldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ADMIN_PASSWORD=JonSn0w
      - LDAP_TLS_VERIFY_CLIENT=try
    hostname: "example.org"
    command: [--loglevel, trace]
```

Run it using `docker-compose up ldap`.

With this I can increase my testing. Here's the first part of the testing you suggested (using 2f88e03b9a7cd16b33a0a8feca9e472f593ca2e3):
* macOS, `ldap://` connection: No leak
* macOS, `ldaps://` connection: Leak is present
* macOS, `default-features=false` (`ldap://`): ???

I will try with Windows after lunch.

**Comment by inejge** [comment] 2020-05-22 18:04
Great, once you have the complete test matrix of platforms and connection types with the fixed `ldap3` version you can report it back to tokio-rs/tokio#2554. So far, it looks like an issue with Secure Transport bindings to `native-tls`. Maybe something in the way in which `ldap3` uses TLS or manages connections triggers the leak?

**Comment by nbigaouette** [comment] 2020-05-22 20:11
Surprisingly, on Windows I see the leak with _and_ without TLS!

`ldaps://`:
<img width="1226" alt="Screen Shot 2020-05-22 at 4 05 56 PM" src="https://user-images.githubusercontent.com/112988/82705897-828ace00-9c46-11ea-9653-930af2b1b37e.png">

`ldap://`:
<img width="1228" alt="Screen Shot 2020-05-22 at 4 08 09 PM" src="https://user-images.githubusercontent.com/112988/82705922-920a1700-9c46-11ea-992d-4a1f0d46b182.png">

`default-features=false` (`ldap://`):
<img width="1221" alt="Screen Shot 2020-05-22 at 4 10 55 PM" src="https://user-images.githubusercontent.com/112988/82706073-e2817480-9c46-11ea-99cb-910029ef3c11.png">

**Comment by inejge** [comment] 2020-05-22 21:04
Now _that's_ confusing... I'll try to find a Windows box tomorrow to see if I can replicate the leak.

**Comment by nbigaouette** [comment] 2020-05-22 21:10
Check the `vagrant` branch, there is a `Vagrantfile` that allows provisionning a virtualbox VM. A simple `vagrant up` in the `windows` directory should create a VM that can build the crate. You'll need vagrant and the windows iso (from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/).

**Comment by inejge** [comment] 2020-05-23 15:45
FYI (Windows 7 x64):

![async-conn-test](https://user-images.githubusercontent.com/1049870/82734643-91dc4b00-9d1c-11ea-9156-7efc21301157.png)

No leak. I'll try with the Win10 Vagrant image on Monday. Meanwhile, you can report your findings in the Tokio issue (not that it's perfectly clear what's happening, at least not to me, but still.)

**Comment by inejge** [comment] 2020-05-25 13:00
Okay, I managed to spin up a couple of VMs and do more testing. __TLDR:__ you can avoid the leak by closing the connection with `unbind()` instead of dropping it. I've tested and confirmed it on all platforms.

The fix in `select-exit` lets you use `drop()` without triggering the leak. Please retest.

**Comment by nbigaouette** [comment] 2020-05-25 15:29
I am testing right now your suggestion. See commit 8f18292757ee2ef82476eac9e6178fc2 in the `unbind` branch: https://github.com/nbigaouette/ldap3-issue47/blob/8f18292757ee2ef82476eac9e6178fc2/src/main.rs#L17-L28

* macOS, `ldaps://` --> I still see the leak :(
* macOS, `ldap://` --> No leak
* Windows 10, `ldaps://` --> No leak!! 🎉 
* Windows 10, `ldap//` --> No leak!

But then, even if I comment the `unbind()`, `drop()` and `handle.await` I don't get a leak (on Windows, ldaps).

All this is so confusing... :(

**Comment by nbigaouette** [comment] 2020-05-25 16:19
I'm redoing the tests on Windows as I am confused by which version leaks and which doesn't.

Instead of measuring the memory profile using Visual Studio (as was the case in my previous comment) I've measured it using Process Explorer. I suspect Visual Studio was not reloading the rebuilt binary between runs and was running the same binary for each runs...

Bisecting the `ldap3-issue47` repo, I got leakage in b5736dc but not in 2a5fb4c (the following commit). Commit [2a5fb4c](https://github.com/nbigaouette/ldap3-issue47/commit/2a5fb4c7abcb9281d46692f311682ca7bf9e80b3) simply patch `ldap3`'s version from crates.io's `0.7.0-alpha.7` to 2f88e03b9a7cd16b33a0a8feca9e472f593ca2e3. Note that the example repo code at that commit is dropping the `ldap` object but isn't awaiting the tokio task handle. See:
https://github.com/nbigaouette/ldap3-issue47/blob/2a5fb4c7abcb9281d46692f311682ca7bf9e80b3/src/main.rs#L24-L29

**Comment by inejge** [comment] 2020-05-25 18:20
Try monitoring the macOS program with `top` or `ps alx`, not Instruments. The former gives you a single number for memory, while the latter displays the familiar VSIZE and RSS. For the Windows version, I also used the Process Explorer.

In my testing:

1. No version of `ldap3` will leak if you use `unbind()` to close the connection.
2. `Ldap3` without 2f88e03 (the select loop exit fix) will leak if the `ldap` handle is dropped without calling `unbind()`.

Whether you call `unbind()` or not, explicitly dropping `ldap` is unnecessary; it will be dropped at the end of the loop. Also, awaiting `handle` is something of a red herring: it demonstrates the select loop bug if you do it, but you don't have to.

It seems to me that your test harness is getting a bit complicated, with its multitude of branches for test variants. I'll post a PR for your `unbind` branch which lets you invoke all combinations of the axes (fixed/unfixed ldap3) and (unbind, drop) from a single branch, just by selecting the corresponding feature and a binary.

**Comment by nbigaouette** [comment] 2020-05-25 20:59
Thanks for the PR, yes the history was becoming messy! :D

I have added a simple script (`process_info.sh`) to use `ps` to show the memory usage. Should work on both linux and mac.

I've run the four commands and monitored using the script (42f4f103816f699b2a12be6464213cc7). I've let the code run for 1 minute each.

* `cargo run --features no-loop-fix --bin ldap3-unbind-orig`: [ldap3_process_info_20200525_16h40.log.gz](https://github.com/inejge/ldap3/files/4678797/ldap3_process_info_20200525_16h40.log.gz)
* `cargo run --features with-loop-fix --bin ldap3-unbind-fixed`: [ldap3_process_info_20200525_16h43.log.gz](https://github.com/inejge/ldap3/files/4678798/ldap3_process_info_20200525_16h43.log.gz)
* `cargo run --features no-loop-fix --bin ldap3-drop-orig`: [ldap3_process_info_20200525_16h44.log.gz](https://github.com/inejge/ldap3/files/4678799/ldap3_process_info_20200525_16h44.log.gz)
* `cargo run --features with-loop-fix --bin ldap3-drop-fixed`: [ldap3_process_info_20200525_16h45.log.gz](https://github.com/inejge/ldap3/files/4678800/ldap3_process_info_20200525_16h45.log.gz)

They all leaked on macOS.

Some simple stats:


```shell
❯ cat ldap3_process_info_20200525_16h40.log.gz | gunzip | xsv stats | xsv table
field    type     sum                 min                             max                             min_length  max_length  mean               stddev
         NULL                                                                                         0           0
ELAPSED  Unicode                      00:00                           01:00                           5           5
PAGEIN   Integer  0                   0                               0                               1           1           0                  0
VSZ      Integer  10955626576         4357800                         4358324                         7           7           4357846.688941914  149.28210967922257
RSS      Integer  13959172            4596                            5972                            4           4           5552.574383452654  259.76062858869955
%CPU     Float    11130.899999999947  3.4                             21.3                            3           4           4.427565632458229  1.1951572432055686
%MEM     Float    0                   0                               0                               3           3           0                  0
COMMAND  Unicode                      target/debug/ldap3-unbind-orig  target/debug/ldap3-unbind-orig  30          30
```
* VSZ leaked: 524 kB
* RSS leaked: 1376 kB


```shell
❯ cat ldap3_process_info_20200525_16h43.log.gz | gunzip | xsv stats | xsv table
field    type     sum                 min                              max                              min_length  max_length  mean               stddev
         NULL                                                                                           0           0
ELAPSED  Unicode                      00:00                            00:59                            5           5
PAGEIN   Integer  0                   0                                0                                1           1           0                  0
VSZ      Integer  9731083752          4357804                          4358328                          7           7           4357852.105687423  151.30506615735462
RSS      Integer  12298424            4612                             5876                             4           4           5507.579041648002  218.4051177892996
%CPU     Float    10041.700000000044  0.5                              7.4                              3           3           4.496954769368567  0.5926325143824926
%MEM     Float    0                   0                                0                                3           3           0                  0
COMMAND  Unicode                      target/debug/ldap3-unbind-fixed  target/debug/ldap3-unbind-fixed  31          31
```
* VSZ leaked: 524 kB
* RSS leaked: 1264 kB

```shell
❯ cat ldap3_process_info_20200525_16h44.log.gz | gunzip | xsv stats | xsv table
field    type     sum                 min                           max                           min_length  max_length  mean               stddev
         NULL                                                                                     0           0
ELAPSED  Unicode                      00:00                         01:00                         5           5
PAGEIN   Integer  0                   0                             0                             1           1           0                  0
VSZ      Integer  9426004704          4357792                       4358316                       7           7           4357838.513176137  149.02828169255753
RSS      Integer  10901752            4444                          5512                          4           4           5040.107258437353  290.7356390204032
%CPU     Float    203956.90000000046  19.8                          100                           4           5           94.29352750809069  6.943198289668081
%MEM     Float    0                   0                             0                             3           3           0                  0
COMMAND  Unicode                      target/debug/ldap3-drop-orig  target/debug/ldap3-drop-orig  28          28
```
* VSZ leaked: 524 kB
* RSS leaked: 1068 kB


```shell
❯ cat ldap3_process_info_20200525_16h45.log.gz | gunzip | xsv stats | xsv table
field    type     sum                min                            max                            min_length  max_length  mean               stddev
         NULL                                                                                      0           0
ELAPSED  Unicode                     00:01                          00:59                          5           5
PAGEIN   Integer  0                  0                              0                              1           1           0                  0
VSZ      Integer  9251539200         4341888                        4358320                        7           7           4357766.933584549  944.7365541154365
RSS      Integer  11471364           4116                           5800                           4           4           5403.374470089508  271.90148226962623
%CPU     Float    9225.500000000022  0                              6.3                            3           3           4.345501648610465  0.6147214790600859
%MEM     Float    0                  0                              0                              3           3           0                  0
COMMAND  Unicode                     target/debug/ldap3-drop-fixed  target/debug/ldap3-drop-fixed  29          29
```
* VSZ leaked: 16432 kB
* RSS leaked: 1684 kB

**Comment by nbigaouette** [comment] 2020-05-25 22:41
I've run 42f4f103816f699b2a12be6464213cc7 in my Windows VM. Three of them don't leak, but `cargo run --features no-loop-fix --bin ldap3-drop-orig` _does_ leak 😭 .

<img width="431" alt="Screen Shot 2020-05-25 at 6 39 15 PM" src="https://user-images.githubusercontent.com/112988/82846529-4316e880-9eb7-11ea-8eb8-010e0d30926b.png">

**Comment by inejge** [comment] 2020-05-26 07:40
> Three of them don't leak [on Windows], but `cargo run --features no-loop-fix --bin ldap3-drop-orig` does leak

It's _supposed_ to leak, it's buggy.

> macOS

What are the precise versions of the OS and Xcode? I'm getting very different results (caveat: this is on a very old installation, 10.11.5).

`--features no-loop-fix --bin ldap3-drop-orig`, buggy, leaks:
![macOS-orig-drop](https://user-images.githubusercontent.com/1049870/82871835-721e7000-9f32-11ea-96fa-085ef7d5fe45.png)

`--features with-loop-fix --bin ldap3-drop-fixed`, no leak:
![macOS-fixed-drop](https://user-images.githubusercontent.com/1049870/82872485-68493c80-9f33-11ea-81a6-39ef64f9d63a.png)

The remaining two graphs are similar to the second one, i.e., no leak. I ran

```
while :;do ps alx|grep [l]dap3;sleep 2;done
```

for two minutes, accumulating 60 data points, and used the RSS column.

After all this, I'm satisfied that

1. Generally, using `unbind()` avoids the select loop bug.

2. With the select loop fix, there will be no leak even if you omit `unbind()`.

3. There is something fishy with the macOS/Xcode combo you're using in conjunction with `ldaps://`.

I will push the select loop fix to `master` and close the issue.

**Closed by inejge** 2020-05-26 07:40 UTC

**Comment by nbigaouette** [comment] 2020-05-26 16:22
I am using macOS Catalina 10.15.4 (19E287) and XCode 11.5 (11E608c), both the latest version as of writing this.

Could you publish a new alpha to crates.io? I'd like to start porting my code to it (from 0.6.1). I wish to test our full code in our environment.

Thanks!

**Comment by inejge** [comment] 2020-05-26 18:51
I'll publish 0.7.1 proper in the next day or two. Thanks for the motivation to exercise the code a lot more thoroughly than it would otherwise have been :slightly_smiling_face: I'll try to lay my hands on a Catalina install and run the tests there.

**Comment by nbigaouette** [comment] 2020-05-26 21:47
Look at those beautiful curves!

<img width="795" alt="Screen Shot 2020-05-26 at 5 44 07 PM" src="https://user-images.githubusercontent.com/112988/82953376-aae13800-9f78-11ea-8092-eb3291207409.png">
<img width="783" alt="Screen Shot 2020-05-26 at 5 44 41 PM" src="https://user-images.githubusercontent.com/112988/82953385-ac126500-9f78-11ea-8783-ed35fd6a015a.png">
<img width="696" alt="Screen Shot 2020-05-26 at 5 45 03 PM" src="https://user-images.githubusercontent.com/112988/82953386-acaafb80-9f78-11ea-83e3-51841fdf0868.png">

My agent has been running for more than half an hour with a nice flat line for memory usage. You see the 1 req/5 sec in the CPU usage. That's around ~500 requests total.

This is using b1da0884df6925c6812d334165a5aa5a2714b4d3.

Thanks a lot for your help!! 👍
